twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'form/fields.html.twig'
    globals:
        postShortcut: '%postShortcut%'
        profiles: '%profiles%'
        comments: '%comments%'

when@test:
    twig:
        strict_variables: true
