# .platform.app.yaml
name: 'your-symfony-app'
type: 'php:8.1'
disk: 2048
web:
  locations:
    '/':
      root: 'public'
      passthru: '/index.php'

dependencies:
  php:
    composer/composer: "^2"

relationships:
  database: "database1:mariadb:10.6"

